---
# Creates a Gitlab Instance
- name: Install and Provision Gitlab
  hosts: gitlabservers
  become: true
  vars_files:
    - vars/gitlab.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible
    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        msg: "/etc/no-ansible exists - skipping un on this node"
    - name: Install SELinux packages
      package:
        name: python3-policycoreutils.noarch
        state: present

  roles:
    - role: geerlingguy.gitlab
      state: present

  post_tasks:
    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
